version: '3'
services:      
  db:
    image: mariadb:10.3
    ports:
      - 3306:3306
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    - "MYSQL_ROOT_PASSWORD="
    - "MYSQL_DATABASE=pusher"
volumes:
    db-data: {}