version: '3'
services:      
  db:
    image: mariadb:10.3
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    - "MYSQL_ROOT_PASSWORD="
    - "MYSQL_DATABASE=pusher"
  web:
    image: openjdk:8
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:8081:8080
    command: ./gradlew bootRun
volumes:
    db-data: {}